name: quizly-dev-db
services:
  postgres-dev:
    image: postgres:18
    container_name: postgres_dev_container
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data/pgdata
  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin_dev_container
    ports:
      - 6060:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: '5050'
        gid: '5050'
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444
configs:
  pgadmin-pgpass:
    content: |
      postgres-dev:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Quiz-Builder DB",
            "Group": "Servers",
            "Host": "postgres-dev",
            "Port": 5432,
            "MaintenanceDB": "${POSTGRES_DB}",
            "Username": "${POSTGRES_USER}",
            "PassFile": "/config/pgpass"
          }
        }
      }

